---
- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add InfluxDB repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

- name: Install InfluxDB packages
  apt: name=influxdb state=present
  register: influxdb_installed

- name: Install InfluxDB Python 2.7 module
  apt: name=python-influxdb state=present

- name: Modify InfluxDB hostname
  replace:
    dest=/etc/influxdb/influxdb.conf
    regexp='hostname = "localhost"'
    replace='hostname = "{{ ansible_hostname }}"'
    backup=yes

- name: Enable InfluxDB on boot'
  service: name=influxdb enabled=yes

- name: Start the InfluxDB service
  when: influxdb_installed|changed
  service: name=influxdb state=restarted

- name: poke a hole for port 8086 in the ufw firewall
  ufw: rule=allow port=8086

- name: Add a database for the monitoring data points
  influxdb_database:
    hostname: "{{ansible_ssh_host}}"
    username: "{{admin_user}}"
    password: "{{admin_password}}" 
    database_name: "{{dbname}}"
    state: present


