---
# file site.yml
# baas andible playbook
- include: pre-config.yml
- include: all-hosts.yml
#- include: zfs-install.yml
- include: docker-kernel.yml
- include: docker-host.yml
- include: kubernetes-master.yml
#- include: kubernetes-worker.yml
